<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends EntityRepository
{

    public function getList($limit, $order, $offset, $keyword)
    {
        $qb = $this
            ->createQueryBuilder('p')
            ->select('p')
            ->orderBy('p.name', $order);

        if ($keyword) {
            $qb = $qb
                ->where('p.name LIKE :keyword')
                ->setParameter('keyword', '%' . $keyword . '%');
        }

        $qb = $qb
            ->setFirstResult(($offset - 1) * $limit)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

        return $qb;
    }
}
