security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        create_user:
            pattern: ^/users
            stateless: true
            methods: [POST]
            security: false

        create_token:
            pattern: ^/auth-token
            stateless: true
            methods: [POST]
            security: false

        api:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
